In [27]:
import pandas as pd

In [36]:
df_raw_test_1 = pd.read_csv('./raw_dataset/Test_case_1.csv')

C:\Users\Khalid\AppData\Local\Temp\ipykernel_1688\2106927555.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98) have mixed types. Specify dtype option on import or set low_memory=False.
  df_raw_test_1 = pd.read_csv('./raw_dataset/Test_case_1.csv')

In [37]:
df_raw_test_1.describe()

,1,Unnamed: 1,Unnamed: 2,2,Unnamed: 4,Unnamed: 5,3,Unnamed: 7,Unnamed: 8,4,...,Unnamed: 89,31,Unnamed: 91,Unnamed: 92,32,Unnamed: 94,Unnamed: 95,33,Unnamed: 97,Unnamed: 98
count,17524,17524,17524,25895,25895,25895,11749,11749,11749,20850,...,22968,22411,22411,22411,19084,19084,19084,12424,12424,12424
unique,17524,10522,17524,25895,15557,25895,11749,8504,11749,20850,...,22968,22411,12334,22411,19084,12997,19084,12424,9960,12424
top,Time,"152,7055",Stroke,Time,"143,3849",Stroke,Time,"139,7149",Stroke,Time,...,Stroke,Time,"165,2384",Stroke,Time,"164,2068",Stroke,Time,"153,2062",Stroke
freq,1,29,1,1,41,1,1,15,1,1,...,1,1,26,1,1,20,1,1,11,1

In [38]:
df_raw_test_1.head()

,1,Unnamed: 1,Unnamed: 2,2,Unnamed: 4,Unnamed: 5,3,Unnamed: 7,Unnamed: 8,4,...,Unnamed: 89,31,Unnamed: 91,Unnamed: 92,32,Unnamed: 94,Unnamed: 95,33,Unnamed: 97,Unnamed: 98
0,Time,Force,Stroke,Time,Force,Stroke,Time,Force,Stroke,Time,...,Stroke,Time,Force,Stroke,Time,Force,Stroke,Time,Force,Stroke
1,sec,N,mm,sec,N,mm,sec,N,mm,sec,...,mm,sec,N,mm,sec,N,mm,sec,N,mm
2,0,"0,03655751","3,333333E-05",0,"0,7931392","3,333333E-05",0,"1,265208","3,333333E-05",0,...,"3,333333E-05",0,"0,8773804","3,333333E-05",0,"0,8058548",0,0,"1,16984","3,333333E-05"
3,"0,01","0,04132589","0,0001333333","0,01","0,7804235","0,0001666667","0,01","1,266797","0,0001333333","0,01",...,"0,0001333333","0,01","0,890096","0,0001333333","0,01","0,8010864","0,0001333333","0,01","1,185735","0,0001333333"
4,"0,02","0,03655751","0,0004666667","0,02","0,7677078","0,0006333333","0,02","1,257261","0,0005333333","0,02",...,"0,0005","0,02","0,9012222","0,0005","0,02","0,8042653","0,0005666667","0,02","1,196861","0,0005333333"

In [39]:
df_melted = df_raw_test_1[['1', 'Unnamed: 1', 'Unnamed: 2']]

In [40]:
df_melted.head(10)

      1  Unnamed: 1    Unnamed: 2
0  Time       Force        Stroke
1   sec           N            mm
2     0  0,03655751  3,333333E-05
3  0,01  0,04132589  0,0001333333
4  0,02  0,03655751  0,0004666667
5  0,03  0,02861023   0,001366667
6  0,04  0,03019969        0,0024
7  0,05  0,03814697   0,003433333
8  0,06  0,05086263   0,004366667
9  0,07  0,06516775   0,005166667

In [41]:
df_melted.rename(columns={'1': 'batch_1', 'Unnamed: 1': 'batch_1', 'Unnamed: 2': 'batch_1'}, inplace=True)

C:\Users\Khalid\AppData\Local\Temp\ipykernel_1688\3837865709.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_melted.rename(columns={'1': 'batch_1', 'Unnamed: 1': 'batch_1', 'Unnamed: 2': 'batch_1'}, inplace=True)

In [42]:
df_melted

      batch_1     batch_1       batch_1
0        Time       Force        Stroke
1         sec           N            mm
2           0  0,03655751  3,333333E-05
3        0,01  0,04132589  0,0001333333
4        0,02  0,03655751  0,0004666667
...       ...         ...           ...
38927     NaN         NaN           NaN
38928     NaN         NaN           NaN
38929     NaN         NaN           NaN
38930     NaN         NaN           NaN
38931     NaN         NaN           NaN

[38932 rows x 3 columns]

In [ ]:
# remove row 1
df_melted = df_melted.drop(df_melted.index[1])

      batch_1     batch_1       batch_1
0        Time       Force        Stroke
2           0  0,03655751  3,333333E-05
3        0,01  0,04132589  0,0001333333
4        0,02  0,03655751  0,0004666667
5        0,03  0,02861023   0,001366667
...       ...         ...           ...
38927     NaN         NaN           NaN
38928     NaN         NaN           NaN
38929     NaN         NaN           NaN
38930     NaN         NaN           NaN
38931     NaN         NaN           NaN

[38931 rows x 3 columns]

In [44]:
df_melted

      batch_1     batch_1       batch_1
0        Time       Force        Stroke
2           0  0,03655751  3,333333E-05
3        0,01  0,04132589  0,0001333333
4        0,02  0,03655751  0,0004666667
5        0,03  0,02861023   0,001366667
...       ...         ...           ...
38927     NaN         NaN           NaN
38928     NaN         NaN           NaN
38929     NaN         NaN           NaN
38930     NaN         NaN           NaN
38931     NaN         NaN           NaN

[38931 rows x 3 columns]

In [ ]:
import pandas as pd
from pandasql import sqldf

# Let's assume 'df' is the name of your original dataframe
df = pd.read_csv('99 dataset finally - Sheet1.csv')

# 1. Define a lambda function for easier querying
pysqldf = lambda q: sqldf(q, globals())

query = """

SELECT DISTINCT(RUN) 
from df

"""

sql_results = pysqldf(query)

print(sql_results)

    Run
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
10   11
11   12
12   13
13   14
14   15
15   16
16   17
17   18
18   19
19   20
20   21
21   22
22   23
23   24
24   25
25   26
26   27
27   28
28   29
29   30
30   31
31   32
32   33